name: Discord Notification

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificação para o Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"Novo evento no repositório! Commit ou PR realizada.\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}